from .user import UserViewSet
from .usuario import UsuarioViewSet
from .bebida import BebidaViewSet
from .carrinho import CarrinhoViewSet
from .carrinhoItem import CarrinhoItemViewSet
from .combo import ComboViewSet
from .endereco import EnderecoViewSet
from .feedback import FeedbackViewSet
from .itempedido import ItemPedidoViewSet
from .pedido import PedidoViewSet
from .pizza import PizzaViewSet
from .produto import ProdutoViewSet
from .reserva import ReservaViewSet