# Generated by Django 5.1.7 on 2025-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, verbose_name='passage_id'),
        ),
    ]
