# Generated by Django 5.1.7 on 2025-09-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
