# Generated by Django 5.1.7 on 2025-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('administrador', 'Administrador'), ('atendente', 'Atendente'), ('pizzaiolo', 'Pizzaiolo'), ('entregador', 'Entregador'), ('cliente', 'Cliente')], max_length=20)),
            ],
        ),
    ]
