# Generated by Django 5.1.7 on 2025-10-22 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='endereco',
            new_name='bairro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tempo_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.JSONField(default=12, help_text='Lista de itens do pedido (pizzas, bebidas, etc)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento_status',
            field=models.CharField(blank=True, default='pendente', max_length=32),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tempo_entrega_max',
            field=models.PositiveIntegerField(blank=True, help_text='Estimativa máxima em minutos', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tempo_entrega_min',
            field=models.PositiveIntegerField(blank=True, help_text='Estimativa mínima em minutos', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='uf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('em_entrega', 'Em Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='confirmado', max_length=32),
        ),
    ]
