# Generated by Django 5.1.7 on 2025-10-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_endereco_pedido_bairro_remove_pedido_carrinho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(null=True),
            preserve_default=False,
        ),
    ]
