# Generated by Django 5.1.7 on 2025-08-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_endereco_pedido_itempedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
            preserve_default=False,
        ),
    ]
