# Generated by Django 5.1.7 on 2025-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
