# Generated by Django 5.2.8 on 2025-11-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_reserva_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='URL da imagem do avatar', max_length=512, null=True, verbose_name='avatar'),
        ),
    ]
