from .user import UserSerializer
from .usuario import UsuarioSerializer
from .bebida import BebidaSerializer
from .carrinho import CarrinhoSerializer
from .carrinhoItem import CarrinhoItemSerializer
from .combo import ComboSerializer
from .endereco import EnderecoSerializer
from .itempedido import ItemPedidoSerializer
from .pedido import PedidoSerializer
from .pizza import PizzaSerializer
from .produto import ProdutoSerializer
from .reserva import ReservaSerializer