from .user import User
from .usuario import Usuario
from .bebida import Bebida
from .carrinho import Carrinho 
from .carrinhoItem import CarrinhoItem
from .combo import Combo
from .endereco import Endereco
from .feedback import Feedback
from .itempedido import ItemPedido
from .pedido import Pedido
from .pizza import Pizza
from .produto import Produto
from .reserva import Reserva